# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.15.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "hub/package-lock.json" }}-{{ checksum "reader/package-lock.json" }}-{{ checksum "admin/package-lock.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
            - hub/node_modules
            - reader/node_modules
            - admin/node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}-{{ checksum "hub/package-lock.json" }}-{{ checksum "reader/package-lock.json" }}-{{ checksum "admin/package-lock.json" }}

      - run: mkdir $HOME/.config

      # run tests!
      - run: npm run test

      - run: npm run codecovUpload
